version: '3'
services:
  webpacker:
    build: .
    command: bash -c "rm -rf /usr/src/app/public/packs; /usr/src/app/bin/webpack-dev-server"
    ports:
      - '3035:3035'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - webpacker
      - database

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
